services:
  - type: web
    name: indo-american-connect
    env: node
    plan: starter
    buildCommand: SHARP_IGNORE_GLOBAL_LIBVIPS=1 NPM_CONFIG_PRODUCTION=false npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: NODE_VERSION
        value: "20.19.0"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: "https://ccvizqbfulhlqtoabddo.supabase.co"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdml6cWJmdWxobHF0b2FiZGRvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjE5MzM3MCwiZXhwIjoyMTAxNzY5MzcwfQ.Pq_0FrXXLtXBBgGvLh9XRWkZ-l1JqnYhuq2ey6ztSMY"
      - key: CLOUDINARY_CLOUD_NAME
        fromService:
          name: cloudinary
          key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromService:
          name: cloudinary
          key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromService:
          name: cloudinary
          key: CLOUDINARY_API_SECRET
      - key: JWT_SECRET
        value: change-me
      - key: ADMIN_USERNAME
        value: ias
      - key: ADMIN_PASSWORD_HASH
        value: $2b$10$nswerg1HOlt3G.wSBhoxeOLuMcqpO8DJn2k4nqvJ0ubI.rsjes.Bm
    rootDir: .
    autoDeploy: true
    plan: free
