services:
  - type: web
    name: indo-american-connect
    env: node
    plan: starter
    buildCommand: SHARP_IGNORE_GLOBAL_LIBVIPS=1 NPM_CONFIG_PRODUCTION=false npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: NODE_VERSION
        value: "20.19.0"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: "https://ccvizqbfulhlqtoabddo.supabase.co"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdml6cWJmdWxobHF0b2FiZGRvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjE5MzM3MCwiZXhwIjoyMTAxNzY5MzcwfQ.Pq_0FrXXLtXBBgGvLh9XRWkZ-l1JqnYhuq2ey6ztSMY"
      - key: CLOUDINARY_CLOUD_NAME
        value: "o0bhyhix"
      - key: CLOUDINARY_API_KEY
        value: "497552822935358"
      - key: CLOUDINARY_API_SECRET
        value: "U-pZ_xqFuDE89UfigMvX1GOwwUo"
      - key: JWT_SECRET
        value: 8c13bab6bacacf20f6135c31e9cef154254fb001b02d8ae62f9168f3bd192b1a
      - key: ADMIN_USERNAME
        value: IAS
      - key: ADMIN_PASSWORD_HASH
        value: $2b$10$bvmL3InDCx/c8b3f1f4nTu08zXVMCUErZNcesGCu.2I7y4EmsNwam
    rootDir: .
    autoDeploy: true
    plan: free
