-- Comprehensive Supabase Database Schema for Indo American School
-- Copy and run this entire SQL script in your Supabase SQL Editor (SQL Editor -> New query -> Run)

-- 1. Announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT DEFAULT 'general',
    urgent INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Events (Create table + Add missing columns if table already exists)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    date TEXT,
    time TEXT,
    venue TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.events ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS venue TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS image_url TEXT;

-- 3. Hero Slides
CREATE TABLE IF NOT EXISTS public.hero_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subtitle TEXT,
    description TEXT,
    accent TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS subtitle TEXT;
ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS accent TEXT;
ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- 4. Gallery
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    category TEXT DEFAULT 'general',
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.gallery ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.gallery ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.gallery ADD COLUMN IF NOT EXISTS image_url TEXT;

-- 5. Site Images
CREATE TABLE IF NOT EXISTS public.site_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_key TEXT UNIQUE,
    label TEXT,
    category TEXT,
    image_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. Teacher Applications
CREATE TABLE IF NOT EXISTS public.teacher_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    post_applied TEXT,
    qualification TEXT,
    experience TEXT,
    resume_url TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS post_applied TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS qualification TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS experience TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS resume_url TEXT;
ALTER TABLE public.teacher_applications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- 7. Documents
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    category TEXT,
    file_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. Past Events
CREATE TABLE IF NOT EXISTS public.past_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    date TEXT,
    year INTEGER,
    main_image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. Past Event Photos
CREATE TABLE IF NOT EXISTS public.past_event_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    past_event_id BIGINT,
    image_url TEXT,
    caption TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 10. Admission Enquiries
CREATE TABLE IF NOT EXISTS public.admission_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT,
    parent_name TEXT,
    email TEXT,
    phone TEXT,
    class_applied TEXT,
    additional_info TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 11. Contact Messages
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    phone TEXT,
    subject TEXT,
    message TEXT,
    read INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 12. Students, Classes, Marks, Attendance
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    roll_number TEXT,
    class_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    section TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    subject TEXT,
    marks_obtained REAL,
    max_marks REAL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    date TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Disable RLS on all tables so backend Service Role / Anon keys can freely read and write
ALTER TABLE public.announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.past_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.past_event_photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admission_enquiries DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.students DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.marks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
